### ISSUE TITLE
Weekly Scrum - Dec 4

### ISSUE THREAD

**Issue by Hoveywan** [FARHAN-MAHAMUD/SYSC-4806-Project#72]

**Comment by PAVafaie** [comment]
What have I done this week?

* Worked on improving UI/UX of frontend - making it so we can add/remove books by clicking on them in the list https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/67
* Refactor, small improvements https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/65

What will I do next week?

* Finish UI changes for https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/67
* Refactoring as needed once complete

**Comment by FARHAN-MAHAMUD** [comment]
What have I done this week?
- Fixed front end bugs concerning the books in the inventory and the user's cart
- Fixed a bug where a user can add or remove a negative amount of books that can mess up the amount stored within the database https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/63

What will I do next week?
- Finalize JavaDoc and clean up code to remove any unnecessary lines https://github.com/FARHAN-MAHAMUD/SYSC-4806-Project/issues/65

**Comment by Hoveywan** [comment]
What have I done this week?

- Fixed homepage and added it into the website flow as the first website reached when logging in. #64 
- Began editing javadoc and code for my created/edited files from previous milestones #65 

What will I do next week?

- Finish adding javadoc and cleaning up code, finalize all methods and files for milestone 3. #65

**Comment by subearjama** [comment]
What have I done this week?
* Worked on putting accounts (owner, user) linked to the users stored in the repository to fix recommendation feature #66 
* Along with some minor fixes to the structure

What will I do next week?
* Finish the changes for accounts (owner, user) linked to the users stored in the repository #66 
* Add some JavaDocs and clean up code, along with some additional fixes to complete this milestone #65 

What is holding me back? (if applicable)
* N/A

**Comment by ihasnaou** [comment]
What have I done this week?

- Add a pop-up when checking out that lists the content of the cart before buying
- Minor refactoring

What will I do next week?

- Some more refactoring, adding comments, javadoc, etc...
